name: Build App
on:
  push:
    branches: [ main ]
jobs:
  buildapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint --ext .js
      - name: Run tests
        run: npm test
      - name: Build app
        run: npm run build
      - name: Notify in Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
                  ${{ github.actor }} created commit:
                  Commit message: ${{ github.event.commits[0].message }}

                  Repository: ${{ github.repository }}

                  See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
